Models/Inquilino.cs
using System.ComponentModel.DataAnnotations;

namespace proyectoInmobiliaria.NET.Models;

public class Inquilino
{
    [Display(Name = "Id")]

    public int id { get; set; }

    [Display(Name = "Nombre")]

    public string? nombre { get; set; }

    [Display(Name = "Apellido")]

    public string? apellido { get; set; }

    [Display(Name = "DNI")]

    public string? dni { get; set; }

    [Display(Name = "Email")]

    public string? email { get; set; }

    [Display(Name = "Celular")]

    public string? celular { get; set; }

    [Display(Name = "Estado")]
    
    public Boolean estado { get; set; }
    
    override
    public String ToString() => $"{apellido}, {nombre}";
}

Controllers/InquilinoController.cs
using System.Configuration;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using proyectoInmobiliaria.NET.Models;

namespace proyectoInmobiliaria.NET.Controllers;


[Authorize]
public class InquilinoController : Controller
{

    RepositorioInquilino repo;
    public InquilinoController()
    {
        repo = new RepositorioInquilino();
    }

    public IActionResult Index()
    {
        var lista = repo.ObtenerTodos();
        return View(lista);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Inquilino inquilino)
    {
        try
        {
            repo.Alta(inquilino);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception)
        {
            return View(inquilino);
        }
    }

    [Authorize(Policy = "Administrador")]
    public IActionResult Eliminar(int id)
    {
        try
        {
            repo.Baja(id);
            TempData["Ok"] = "Inquilino eliminado.";
        }
        catch (MySqlException ex) when (ex.Number == 1451)
        {
            TempData["Error"] = "No se puede eliminar: tiene inmuebles y/o contratos asociados.";
        }
        catch (Exception)
        {
            TempData["Error"] = "Ocurrió un error al eliminar el inquilino.";
        }

        return RedirectToAction(nameof(Index));
    }


    public ActionResult Edit(int id)
    {
        try
        {
            var entidad = repo.ObtenerPorId(id);
            return View("Edit", entidad);
        }
        catch (Exception)
        {
            throw;
        }
    }

    [HttpPost]
    public IActionResult Edit(Inquilino inquilino)
    {
        try
        {
            repo.Modificacion(inquilino);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception)
        {
            return View(inquilino);
        }
    }

    public IActionResult Detalles(int id)

    {
        var inquilino = repo.ObtenerPorId(id);
        if (inquilino == null)
        {
            return NotFound();
        }

        return View(inquilino);
    }




















}

Views/Inquilino/Create.cshtml
@model proyectoInmobiliaria.NET.Models.Inquilino
@{
    ViewData["Title"] = "Create";
}

<h4>Nuevo Inquilino</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="apellido" class="control-label"></label>
                <input asp-for="apellido" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="dni" class="control-label"></label>
                <input asp-for="dni" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="celular" class="control-label"></label>
                <input asp-for="celular" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
            </div>
            <div class="form-group form-check m-2">
                <input asp-for="estado" class="form-check-input" type="checkbox" />
                <label asp-for="estado" class="form-check-label"></label>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary m-2" />
            </div>
        </form>
    </div>
</div>

<div>
   <a class="btn btn-primary m-2" asp-action="Index">Volver</a>
</div>

Views/Inquilino/Detalles.cshtml
@model proyectoInmobiliaria.NET.Models.Inquilino

@{
    ViewData["Title"] = "Detalles";
}

<h2>Detalles del Inquilino</h2>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.id)</th>
        <td>@Html.DisplayFor(model => model.id)</td>
    </tr>
    <tr>
        <th>@Html.DisplayNameFor(model => model.nombre)</th>
        <td>@Html.DisplayFor(model => model.nombre)</td>
    </tr>
    <tr>
        <th>@Html.DisplayNameFor(model => model.apellido)</th>
        <td>@Html.DisplayFor(model => model.apellido)</td>
    </tr>
    <tr>
        <th>@Html.DisplayNameFor(model => model.dni)</th>
        <td>@Html.DisplayFor(model => model.dni)</td>
    </tr>
    <tr>
        <th>@Html.DisplayNameFor(model => model.celular)</th>
        <td>@Html.DisplayFor(model => model.celular)</td>
    </tr>
    <tr>
        <th>@Html.DisplayNameFor(model => model.email)</th>
        <td>@Html.DisplayFor(model => model.email)</td>
    </tr>
</table>
<div>
    <a class="btn btn-primary m-2" asp-action="Index">Volver</a>
</div>

Views/Inquilino/Edit.cshtml
@model proyectoInmobiliaria.NET.Models.Inquilino
@{
	ViewData["Title"] = "Editar Inquilino";
}

<h4>Editar Inquilino</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" name="IdInquilino" value="@Model.id" />
			<div class="form-group">
				<label asp-for="nombre" class="control-label"></label>
				<input asp-for="nombre" class="form-control" />
				<span asp-validation-for="nombre" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="apellido" class="control-label"></label>
				<input asp-for="apellido" class="form-control" />
				<span asp-validation-for="apellido" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="dni" class="control-label"></label>
				<input asp-for="dni" class="form-control" />
				<span asp-validation-for="dni" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="email" class="control-label"></label>
				<input asp-for="email" class="form-control" />
				<span asp-validation-for="email" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="celular" class="control-label"></label>
				<input asp-for="celular" class="form-control" />
				<span asp-validation-for="celular" class="text-danger"></span>
			</div>
			<div class="form-group form-check m-2 ">
				<input asp-for="estado" class="form-check-input" type="checkbox" />
				<label asp-for="estado" class="form-check-label">Estado</label>
			</div>
			<div class="form-group">
				<input type="submit" value="Guardar" class="btn btn-primary m-2" />
			</div>
		</form>
	</div>
</div>


<div>
	<a class="btn btn-primary m-2" asp-action="Index">Volver</a>
</div>

Views/Inquilino/Index.cshtml
@model IEnumerable<proyectoInmobiliaria.NET.Models.Inquilino>

@{
	ViewData["Title"] = "Home Page";
}

@if (TempData["Ok"] is string ok) {
  <div class="alert alert-success">@ok</div>
}
@if (TempData["Error"] is string err) {
  <div class="alert alert-danger">@err</div>
}


<h1>
	Inquilinos
	<div class="btn-group pull-right">
		<a class="btn btn-primary" asp-action="Create" title="Crear"> Crear </a>
	</div>
</h1>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.nombre)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.apellido)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.dni)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.nombre)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.apellido)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.dni)
				</td>
				<td>
					<div class="btn-group" role="group">
						<a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.id" title="Editar">
							Editar
						</a>
						@if (User.IsInRole("Administrador")) {
							<a class="btn btn-danger btnOpcion" asp-action="Eliminar" asp-route-id="@item.id"
							title="Eliminar">
							Eliminar
						</a>
						}
						<a class="btn btn-secondary" asp-action="Detalles" asp-controller="Inquilino" asp-route-id="@item.id" title="Detalles">
							Detalles
						</a>
					</div>
				</td>
			</tr>
		}	
	</tbody>
</table>